#!/usr/bin/env bash

# Indefinately writes 'I am alive!' to the file /tmp/my_process
# Should pause for 2 seconds
sleep() {
  ! read -rt "$1"
} <> <(:)

while true
do
  echo 'I am alive!'
  sleep 2
done > "${TMPDIR:-/tmp}/my_process"
