#!/usr/bin/env bash
# Display 1-100
# -> 'FizzBuzz when num is multiple of 3 & 5
# -> 'Fizz' when num is multiple of 3
# -> 'Buzz' when num us multiple of 5

for num  in {1..100}
do
if ((num % 15 == 0))
    then
    echo "FizzBuzz"
elif ((num % 5 == 0))
    then
    echo "Buzz"
elif (( num % 3 == 0))
    then
    echo "Fizz"
else
    echo "$num"
fi
done
