#!/usr/bin/env bash
# Display 1-20
# 4 and then 'bad luck from China' -> 4th iteration
# 9 and then 'bad luck from Japan' -> 9th iteration
# 17 and then 'bad luck from Italy' -> 17th iteration

# MUST use while loop
# MUST use case statement

cnt=1
while [ $cnt -le 20 ]
do
case $cnt in
    4) echo $cnt
       echo "bad luck from China"
    ;;
    9) echo $cnt
       echo "bad luck from Japan"
    ;;
    17) echo $cnt
        echo "bad luck from Italy"
    ;;
    *)
        echo $cnt
esac
((cnt++))
done
