#!/usr/bin/env bash
# Display
# (i) Content of current directory
# (ii) In a list format
# (iii) Where only the part of the name after the first dash is displayed
#
# MUST use for loop
# DO NOT display hidden files

for contents in *
do
    echo "$contents" | cut -d'-' -f2
done
